### ISSUE TITLE
Configure which images are to be pushed

### ISSUE THREAD

**Issue by ludovicc** [harbur/captain#23]
Configure which images are to be pushed, e.g. to exclude test images.

I need this functionality soon... I think that it would be simpler if by default test images are never pushed.

**Comment by spiddy** [comment]
The functionality is something I´m looking forward for also. Does a boolean field "disable_push" in captain.yml of specific image seem reasonable? (with default value false)

The auto exclude I find it useful, but rather heuristic, how can you identify which ones are test images? In my case I want to exclude compile images and deploy only runtime ones, but I´m sure there are other use cases that I don´t want to restrict it to specific context.

**Comment by paddie** [comment]
The `disable_push` makes sense, as in:

```yml
hello-world:
  build: Dockerfile
  push: false # default to true
  image: harbur/hello-world
  pre:
    - echo "Preparing hello-world"
  post:
    - echo "Finished hello-world"
hello-world-test:
  build: Dockerfile.test
  push: false
  image: harbur/hello-world-test
  pre:
    - echo "Preparing hello-world-test"
  post:
    - echo "Finished hello-world-test"
  test:
    - docker run -e NODE_ENV=TEST harbur/hello-world-test node mochaTest
    - docker run -e NODE_ENV=TEST harbur/hello-world-test node karmaTest
project-with-build-args:
  build: Dockerfile
  push: false
  image: harbur/buildargs
  build_arg:
    keyname: keyvalue
```
