### ISSUE TITLE
Add support for build time variables

### ISSUE THREAD

**Issue by ludovicc** [harbur/captain#30]
Docker supports now build time variables, it would be great if captain adds support for them too.
For example,
```
hello-world-test:
  build: Dockerfile.test
  image: harbur/hello-world-test
  build_variables:
    NODE_ENV: test
```

```
> docker build --help
Usage:	docker build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile
  --build-arg=[]                  Set build-time variables
[...]
```
