### ISSUE TITLE
Feature request: support test subcommands?

### ISSUE THREAD

**Issue by jmmills** [harbur/captain#60]
It would be nice to be able to breakout tests on a container into sub-commands, this would be useful for CI/CD integration v. Developer workflow.

Example, a python app that might need coverage reports generated in junit, but developers want console tests:
```
app:
  image: myorg/app
  build: Dockerfile
  test:
    default: nosetests --with-coverage --with-timer 
    ci: nosetests --with-xunit --with-coverage 
```

Thus, development workflow for testing would be done with ```captain test``` running the default target, and a CI server could call ```captain test ci``` to run a custom test command.
