### ISSUE TITLE
Support new format for captain.yml

### ISSUE THREAD

**Issue by spiddy** [harbur/captain#7]
Current format of captain.yml is limited, configuration cannot be added per image. Opting for a docker-compose.yml style format where each image gets it's own space on yml.

Example of new format:

```
captain:
  build: Dockerfile
  image: harbur/captain
captain-test:
  build: Dockerfile.test
  image: harbur/captain-test
  test:
    - docker run harbur/captain-test go test github.com/harbur/captain/captain
```
