### ISSUE TITLE
Add support for "pre" & "post" commands

### ISSUE THREAD

**Issue by spiddy** [harbur/captain#8]
In order to wrap non-docker build commands on the build life-cycle of containers preparation the following will be added on the captain.yml format:

```
captain-example:
  build: Dockerfile
  image: harbur/captain-example
  pre:
    - echo "Preparing build"
  post:
    - echo "Cleaning up build"
```
